# This workflow will install Claudia after installing Python dependencies, installs rippled ailding-and-testing-python

name: Claudia

on:
  push:

jobs:
  launch_network_with_claudia:

    runs-on: [self-hosted, heavy]
    container: "ubuntu:24.04"
    steps:
    - run: apt-get update && apt-get install --yes python3-pip python-is-python3
    - uses: actions/checkout@v4
    - name: Build Claudia package
      run: python -m pip install build && python -m build
    - name: Install Claudia package
      run: |
        python -m pip install .
        claudia
    - name: Install rippled with Claudia
      run: claudia rippled install --rippled_branch master
    - name: Start network with Claudia
      run: claudia local-mainnet start
    - name: Stop network with Claudia
      run: claudia local-mainnet stop
