# This workflow will install Claudia after installing Python dependencies, installs rippled ailding-and-testing-python

name: Claudia

on:
  push:

jobs:
  launch_network_with_claudia:

    runs-on: ubuntu-latest
    container: python:3.11
    steps:
    - name: Where are we
      run: |
        ls -l
        # python -m pip install --upgrade pip
        # pip install flake8 pytest
        # if [ -f ./src/claudia/requirements.txt ]; then pip install -r ./src/claudia/requirements.txt; fi
    # - name: Install Claudia locally
    #   run: |
    #     python3 setup.py sdist bdist_wheel
    #     pip install dist/*.tar.gz
    #     rm -fr build/ dist/ claudia.egg-info
    #     claudia
    # - name: Install rippled with Claudia
    #   run: |
    #     claudia rippled install --rippled_branch master
    # - name: Start network with Claudia
    #   run: |
    #     claudia local-mainnet start
    # - name: Stop network with Claudia
    #   run: |
    #     claudia local-mainnet stop
