# This workflow will install Claudia after installing Python dependencies, installs rippled ailding-and-testing-python

name: Claudia

on:
  push:

jobs:
  launch_network_with_claudia:

    runs-on: ubuntu-latest
    container: python:3.11
    steps:
    - uses: actions/checkout@v4
    - name: Install Claudia locally
      # working-directory: claudia
      run: |
        ls -l 
        pip install build && python -m build
        claudia
    - name: Install rippled with Claudia
      run: |
        claudia rippled install --rippled_branch master
    - name: Start network with Claudia
      run: |
        claudia local-mainnet start
    - name: Stop network with Claudia
      run: |
        claudia local-mainnet stop
